# Site settings
title:       squeakyvessel
email:       benjamin@squeakyvessel.com
author:      Benjamin Reitzammer
description: "squeakyvessel - Contains your favourite tagline without a pun"
baseurl:     "/"
url:         "http://squeakyvessel.com"

show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: 'benjmin-r'
twitter_username: benjamin

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title/
paginate: 5
sass:
  compressed: true

gems: [jekyll-paginate]
